#!/bin/bash

export BROKER1=<BROKER1-DNS>
export BROKER2=<BROKER2-DNS>
export BROKER3=<BROKER3-DNS>
export BROKER4=<BROKER4-DNS>

export SCHEMA_REGISTRY=<SCHEMA_REGISTRY-DNS>
export KAFKA_REST=<KAFKA_REST-DNS>
export CONFLUENT_CONTROL_CENTER=<CONFLUENT_CONTROL_CENTER-DNS>

export DB_SERVER=<DB_SERVER-DNS>
export DB_PORT=<DB_PORT>
export DB_NAME=<DB_NAME>
export DB_USER=<DB_USER>
export DB_PW=<DB_PW>
export MAPBOX_STYLE=<MAPBOX_STYLE-ADRESS>
export MAPBOX_TOKEN=<MAPBOX_TOKEN>